version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "9000:80"
    restart: unless-stopped

# docker compose up --build 