    FROM node:alpine

    WORKDIR /app

    COPY package*.json ./

    RUN npm install

    COPY . .

    EXPOSE 3000

    CMD ["npm", "start"] 

    # docker build -t my-express-app:v0.1 .
    # docker run -p 80:3000 my-express-app:v0.1